### PR TITLE
fixes #23 textbox resizing with min-height set

### LINKED ISSUE #23: does not autosize textarea with min-height
Here is an example of the bug: http://codepen.io/tinynow/pen/MyXZNL

### PR DESCRIPTION
**Pull request by anfedorov**
Tested in latest Chrome. Should work in others since minHeight is a pretty old spec. Let me know if I should test manually to confirm.

### CODE REVIEW

**Comment by LeaVerou** [comment]
Hi @anfedorov,

Thanks! 

>  Let me know if I should test manually to confirm.

I would feel more comfortable if you did, at least in Firefox & Safari. Is that ok?

**Comment by anfedorov** [comment]
Of course, will do shortly!

**Comment by anfedorov** [comment]
Tested in Firefox / Safari / Chrome on OS X, and IE / Edge / Firefox / Chrome on Windows. All working great!

**Comment by LeaVerou** [comment]
Awesome, thank you!

**Pull request merged**
