### PR TITLE
Fix calculation for box-sizing on textareas

### PR DESCRIPTION
**Pull request by dpschen**

### CODE REVIEW

**Comment by LeaVerou** [comment]
Hi there, thanks for submitting this PR!
Could you elaborate a bit on this change? Does it fix one of your use cases that was previously broken? I looked at the deploy preview and can't spot any change for `<input>`. I *can* spot the improvement in `<textarea>`. Can't spot any visual change in the testsuite either.

**Comment by dpschen** [comment]
Indeed! I went a bit overboard with also adjusting the method for inputs.
The problem I had was only affecting a textarea. I'll adjust this fix =)

**Comment by LeaVerou** [comment]
Merged, though it worries me a bit that this wasn't there all these years even though the conditional branches off `box-sizing` anyway.

**Comment by dpschen** [comment]
Yes. I'm still not convinced if this is the right — and especially complete – fix, but it seems to be a "more accurate" way to do this, since `offsetHeight` should include padding (but also the border) when height is set to `0`.

I discovered an issue with the `box-sizing` calculation when I tried the `resize` method isolated in a project (the use case is very specific to one `<textarea>` so there was no need for all the extra logic).

I'm having a hard time to extract a good isolated test from that project but if I have some more / other insights I'll share it =)

**Pull request merged**
