### PR TITLE
Moved style transformations to a cloned node

### PR DESCRIPTION
**Pull request by p2kmgcl**
This commit solves #14

I have been analysing the behaviour of stretchy with CSS transitions,
and the problem starts on the "computed styles". When the width or
height values are being animated, the computed value changes do not
occur immediately, and this is why the calculated value is not correct.

Firstly I tried to queue the calculation until the end of the
transition by using setInterval, but the UI felt buggy and flickery, so
I decided to move these transformation to a new node, clone of the
original element, and only apply the result at the end of the process.
This cloned element needs to be added to the DOM, as the browser
computes the changed values, but it can be removed when everything is
calculated.

Aaaand that's all. I know that creating a node, appending it to the DOM,
and removing it may look too heavy, but I have tested in on Chrome and
Firefox and the results are pretty good :)

### CODE REVIEW

**Comment by LeaVerou** [comment]
Hey, sorry for the huge delay!

Wouldn't it be better to just disable the transition while we're measuring, then reapply it after?

**Comment by p2kmgcl** [comment]
No worries :smile: 
Mmmm I have to check that, because I think I tried and did not work, but I am not sure

**Comment by p2kmgcl** [comment]
@LeaVerou I have checked that, and that would be not enough

I like, the idea, but it would need a code rewrite, because there are some parts on the code where measures reads and writes are mixed (like in https://github.com/LeaVerou/stretchy/blob/gh-pages/stretchy.js#L52-L55), and that is what makes the transitions go crazy :smile: 

Do you have any alternative in mind?

**Comment by LeaVerou** [comment]
I don't think you understood what I suggested. What I’m saying is, **remove the transition** *before* any of that happens, then restore it at the end before the function returns.

**Comment by p2kmgcl** [comment]
I did, but I did not explained myself :sweat_smile: 

If you remove the transition, then perform the calculations, and then re-add the transition, the transition does nothing, because the element has been modified during the calculations, while no transition is active.

I simply tried adding `element.style.transition = "none";` at the beginning and `element.style.transition = "";` at the end, and it works, but with flickering animations (it does work for select inputs).

peek 06-10-2017 12-47

**Pull request closed without merging**
