### PR TITLE
Don't depend on document.body until after DomContentLoaded

### PR DESCRIPTION
**Pull request by dustingetz**
When loading this script from <head> e.g. in a single page app, document.body is null, so we can't access it until after domContentLoaded.

### CODE REVIEW

**Comment by dustingetz** [comment]
Something is wrong with this PR

**Comment by dustingetz** [comment]
Reopening, PR is fine, master was way behind gh-pages

**Comment by LeaVerou** [comment]
Sorry for the delay, thanks for the contribution!
However, I think your initial assessment was correct: Something is wrong with this PR. It includes a ton of changes, that I’m sure you did not intend. Could you please look into it?
Thanks!

**Comment by dustingetz** [comment]
Only the final commit is mine, the rest of them is fast-fowarding the master branch which was missing many commits from the gh-pages branch

**Comment by LeaVerou** [comment]
Ok, I’m closing this PR, please send a new one with only your changes (right now reviewing the diff is impossible) because the issue does need to be fixed indeed :)
Thanks for contributing!

**Comment by dustingetz** [comment]
Here is the relevant commit:
https://github.com/dustingetz/stretchy/commit/ac324b87f63096897094b53fd06980d5b6f19f5a

**Pull request closed without merging**
